project:
  type: website

website:
  title: "site-quarto"
  back-to-top-navigation: true
  # reader-mode: true
  sidebar: 
    style: "docked"
  navbar:
    left:
      - href: index.qmd
        text: Plan de Verniquet
      - href: etat-major.qmd
        text: "Carte d'État-Major"

format:
  html:
    page-layout: full
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    toc-expand: true

editor: source

